### ISSUE TITLE
Move WebSite and FTP to the new server

### ISSUE THREAD

**Issue by eloi-isric** [ISRICWorldSoil/SoilGrids250m#40]
The FTP has to be moved before the 2017-08-11. That is the day the contract ends of the present server.
The website (production and development) please, also move it to the new server so I can close the VM where is now.

**Comment by noteven2degrees** [comment]
Dear all

This Friday / Saturday I tried to receive files from the SoilGrid FTP, but downloads stopped in between with the FTP server being not reachable anymore. Reading this thread I suppose this is due to server migration. Do you have any information when and where the data will be available again? Thank you very much!

Best regards
Christian

**Comment by smiller2956** [comment]
To add to the previous comment from noteven2degrees: the "old" ftp is now requiring an authorization login. I am not sure if this apart of the server migration or not. Can you please provide the login if that is now necessary to access the raw soilgrids data.

Thanks,

Stephanie

**Comment by eloi-isric** [comment]
The FTP is now fully functional in the new server. I can't reproduce smiller2956 issue. smiller2956, could you please refresh your browser and make sure you are accessing ftp://ftp.soilgrids.org.
Cheers.

**Comment by smiller2956** [comment]
Thank you for the quick response. I am still having the issue connecting to the ftp server. I spoke with my network administrator and it seems our network is blocked from accessing the soilgrids server. I am using a university network to access and download the soilgrids data. Please help.

Thanks,

Stephanie

**Comment by eloi-isric** [comment]
Solved
